export const TRIP_START = new Date('2026-04-16T22:15:00');

export const CITIES = [
  {
    name: 'Bangkok',
    subtitle: 'City of Angels \u00b7 Golden Temples \u00b7 1 Night',
    dayRange: [1, 3],
    heroImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Bangkok_Night_Wikimedia_Commons.jpg/1600px-Bangkok_Night_Wikimedia_Commons.jpg',
  },
  {
    name: 'Phuket',
    subtitle: 'The Slate \u00b7 Nai Yang Beach \u00b7 5 Nights',
    dayRange: [4, 8],
    heroImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Railay.jpg/1600px-Railay.jpg',
  },
  {
    name: 'Koh Samui',
    subtitle: 'Silavadee \u00b7 Ocean View Pool Villa \u00b7 4 Nights',
    dayRange: [9, 12],
    heroImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/KohPhiPhi.JPG/1600px-KohPhiPhi.JPG',
  },
  {
    name: 'Bangkok \u2014 Grand Finale',
    subtitle: 'Park Hyatt \u00b7 Rooftop Bars \u00b7 Last Night',
    dayRange: [13, 15],
    heroImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Wat_Arun_Ratchawararam_and_Royal_Barge_Procession.JPG/1600px-Wat_Arun_Ratchawararam_and_Royal_Barge_Procession.JPG',
  },
];

export const DAYS = [
  {
    id: 'day1',
    day: 'Day 1',
    date: 'Thu, 16 Apr',
    title: 'Departure Day',
    location: 'London \u2192 Bangkok',
    weather: '',
    items: [
      {
        time: '22:15',
        activity: 'Depart London Gatwick \u2708\ufe0f',
        bookingInfo: [
          'British Airways BA 2231',
          'Ref: Y3K2WE',
          'Seats: 13E & 13D',
          'Premium Economy Semi-Flex',
          '2x23kg checked + cabin bag + handbag',
        ],
      },
    ],
    note: 'Direct overnight flight \u2014 arrive Bangkok 16:05 tomorrow. No connection needed!',
    images: [],
  },
  {
    id: 'day2',
    day: 'Day 2',
    date: 'Fri, 17 Apr',
    title: 'Welcome to Bangkok',
    location: 'Bangkok',
    weather: '34\u00b0C, Humid',
    items: [
      { time: '16:05', activity: 'Touch down in Bangkok \ud83c\uddf9\ud83c\udded \u2014 Direct from Gatwick!' },
      { time: '~16:45', activity: 'Taxi or Airport Rail Link to Ploenchit (~40 mins)' },
      {
        time: '~17:30',
        activity: 'Check in M\u00f6venpick Ploenchit',
        bookingInfo: [
          'M\u00f6venpick BDMS Ploenchit',
          'Conf: 4677.174.955',
          'PIN: 4003',
          'Deluxe King Room \u2014 1 night',
        ],
      },
      { time: '~18:00', activity: 'Freshen up & relax at the hotel' },
      { time: '~19:00', activity: 'Chao Phraya Dinner Cruise \ud83c\udf89 \u2014 Glide past the illuminated Grand Palace, Wat Arun, and riverside temples' },
    ],
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Bangkok_Night_Wikimedia_Commons.jpg/600px-Bangkok_Night_Wikimedia_Commons.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Wat_Arun_Ratchawararam_and_Royal_Barge_Procession.JPG/600px-Wat_Arun_Ratchawararam_and_Royal_Barge_Procession.JPG',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Thai_Food_in_street.JPG/600px-Thai_Food_in_street.JPG',
    ],
  },
  {
    id: 'day3',
    day: 'Day 3',
    date: 'Sat, 18 Apr',
    title: 'Fly to Phuket',
    location: 'Bangkok \u2192 Phuket',
    weather: '35\u00b0C, Sunny',
    items: [
      { time: 'Morning', activity: 'Sleep in & leisurely breakfast at M\u00f6venpick \u2014 recover from the overnight flight' },
      { time: '~10:00', activity: 'Gentle stroll around Ploenchit or relax at the hotel pool' },
      { time: '~10:30', activity: 'Taxi to Suvarnabhumi Airport \u2014 no rush' },
      { time: '11:15', activity: 'Bangkok Airways Lounge \u2014 Free for all passengers' },
      {
        time: '12:35',
        activity: 'PG273 Bangkok \u2192 Phuket \u2708\ufe0f',
        bookingInfo: [
          'Bangkok Airways PG273',
          'Ref: EYK4NV',
          'Seats: 20A & 20B',
          'E-tickets: 829-2310548281 / 282',
          '20kg checked + 7kg carry-on',
        ],
      },
      {
        time: '14:05',
        activity: 'Arrive Phuket \u2014 Check in The Slate \u2600\ufe0f',
        bookingInfo: [
          'The Slate, Phuket',
          'Conf: 4570.457.271 + 6619.503.325',
          'PIN: 3160 / 2273',
          'Pearl Bed Suite \u2014 5 nights (4+1)',
        ],
      },
      { time: 'Evening', activity: 'Settle in \u2014 pool, beach, first sunset cocktails' },
    ],
    note: 'Take it easy after the overnight flight \u2014 save the temples for the return Bangkok visit on Day 14.',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Railay.jpg/600px-Railay.jpg',
      'https://images.unsplash.com/photo-1540202404-a2f29016b523?w=600&q=80',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Bangkok_Night_Wikimedia_Commons.jpg/600px-Bangkok_Night_Wikimedia_Commons.jpg',
    ],
  },
  {
    id: 'day4',
    day: 'Day 4',
    date: 'Sun, 19 Apr',
    title: 'Phang Nga Bay & James Bond Island',
    location: 'Phuket',
    weather: '31\u00b0C, Tropical',
    items: [
      { time: '08:00', activity: 'Phang Nga Bay full-day tour \ud83d\udea4 \u2014 Speedboat through limestone karsts rising from emerald water' },
      { time: '', activity: 'Sea cave canoeing through hidden lagoons at Panak & Hong Island' },
      { time: '', activity: 'James Bond Island \u2014 the iconic needle rock from The Man with the Golden Gun' },
      { time: '', activity: 'Lunch at Koh Panyee \u2014 floating fishing village built on stilts' },
      { time: '', activity: 'Swimming at Naka Island white sand beach' },
      { time: '~17:00', activity: 'Return to The Slate' },
      { time: 'Evening', activity: 'Sunset drinks & seafood on Nai Yang Beach' },
    ],
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Longtail_boat_at_Maya_bay.JPG/600px-Longtail_boat_at_Maya_bay.JPG',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Railay.jpg/600px-Railay.jpg',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
    ],
  },
  {
    id: 'day5',
    day: 'Day 5',
    date: 'Mon, 20 Apr',
    title: 'Spa Day & Old Phuket Town',
    location: 'Phuket',
    weather: '32\u00b0C, Partly Cloudy',
    items: [
      { time: 'Morning', activity: 'Sleep in \u2014 lazy breakfast by the pool \ud83d\ude0c' },
      { time: '10:00', activity: 'Coqoon Spa \u2014 Treehouse Couples\u2019 Massage \ud83d\udc86 \u2014 The Slate\u2019s rainforest canopy spa' },
      { time: '', activity: 'Snorkelling off Nai Yang \u2014 coral reef 100m offshore' },
      { time: '', activity: 'Paddleboarding on calm waters' },
      { time: '', activity: 'Sirinat National Park \u2014 800m mangrove boardwalk' },
      { time: '17:30', activity: 'Nai Yang Beach sunset \ud83c\udf05 \u2014 Coconut shakes, watch planes land overhead' },
      { time: 'Evening', activity: 'Old Phuket Town \u2014 Sino-Portuguese architecture, street art, incredible street food' },
    ],
    note: 'Rest up after yesterday\u2019s Phang Nga adventure. Try mee hokkien and oh-aew shaved ice on Soi Romanee \u2014 the prettiest street in Phuket.',
    images: [
      'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=600&q=80',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Thai_Food_in_street.JPG/600px-Thai_Food_in_street.JPG',
    ],
  },
  {
    id: 'day6',
    day: 'Day 6',
    date: 'Tue, 21 Apr',
    title: 'Phi Phi Islands & Maya Bay',
    location: 'Phuket',
    weather: '31\u00b0C, Sunny',
    items: [
      { time: '07:00', activity: 'Phi Phi Islands speedboat day trip \ud83c\udfd6\ufe0f \u2014 Hotel pickup ~06:30' },
      { time: '', activity: 'Maya Bay \u2014 the famous beach from "The Beach"' },
      { time: '', activity: 'Pileh Lagoon \u2014 swim in an emerald pool surrounded by cliffs' },
      { time: '', activity: 'Snorkelling at Loh Samah Bay' },
      { time: '', activity: 'Viking Cave \u2014 ancient paintings on limestone' },
      { time: '', activity: 'Bamboo Island \u2014 pristine white sand' },
    ],
    note: 'Refreshed after yesterday\u2019s spa day! Bring reef-safe sunscreen & seasickness tablets.',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/KohPhiPhi.JPG/600px-KohPhiPhi.JPG',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Longtail_boat_at_Maya_bay.JPG/600px-Longtail_boat_at_Maya_bay.JPG',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=600&q=80',
    ],
  },
  {
    id: 'day7',
    day: 'Day 7',
    date: 'Wed, 22 Apr',
    title: 'Last Full Day in Phuket',
    location: 'Phuket',
    weather: '31\u00b0C, Warm',
    items: [
      { time: 'Morning', activity: 'Beach morning \u2014 last swim at Nai Yang' },
      { time: 'Afternoon', activity: 'Optional: Thai cooking class \u2014 pad thai, green curry, mango sticky rice' },
      { time: 'Evening', activity: 'Black Ginger Restaurant \ud83d\udda4 \u2014 Fine dining on a raft punted across a lake \u2014 The Slate\u2019s signature' },
    ],
    note: 'Black Ginger needs advance booking \u2014 ask at reception on Day 3. Unforgettable.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80',
    ],
  },
  {
    id: 'day8',
    day: 'Day 8',
    date: 'Thu, 23 Apr',
    title: 'Fly to Koh Samui',
    location: 'Phuket \u2192 Koh Samui',
    weather: '31\u00b0C, Clear',
    items: [
      { time: '08:00', activity: 'Final Slate breakfast' },
      { time: '12:00', activity: 'Check out' },
      {
        time: '13:00',
        activity: 'PG254 Phuket \u2192 Koh Samui \u2708\ufe0f',
        bookingInfo: [
          'Bangkok Airways PG254',
          'Ref: EYK4NV',
          'Seats: 12A & 12B',
          '20kg checked + 7kg carry-on',
        ],
      },
      {
        time: '14:00',
        activity: 'Arrive Silavadee Pool Spa Resort \ud83c\udf34',
        bookingInfo: [
          'Silavadee Pool Spa Resort',
          'Conf: 999240277021074',
          'PIN: 6894',
          'Scenic Ocean View Pool Villa \u2014 4 nights',
        ],
      },
      { time: '17:30', activity: 'First sunset from our private infinity pool \u2014 Overlooking the Gulf of Thailand' },
    ],
    note: 'Be packed and ready at noon sharp \u2014 the 13:00 flight is tight. Airport is only 10 mins from The Slate.',
    images: [
      'https://images.unsplash.com/photo-1540202404-a2f29016b523?w=600&q=80',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=600&q=80',
    ],
  },
  {
    id: 'day9',
    day: 'Day 9',
    date: 'Fri, 24 Apr',
    title: 'Explore the Island',
    location: 'Koh Samui',
    weather: '31\u00b0C, Clear',
    items: [
      { time: '10:00', activity: 'Island exploration by private driver \u2014 pick 2\u20133 stops that appeal most' },
      { time: '', activity: 'Big Buddha Temple \u2014 12-metre golden statue on a causeway' },
      { time: '', activity: 'Na Muang Waterfalls \u2014 swim in the natural jungle pool' },
      { time: '13:00', activity: 'Lunch at Fisherman\u2019s Village, Bophut \u2014 Charming old town' },
      { time: 'Afternoon', activity: 'Free time \u2014 pool, beach, or optional Secret Buddha Garden / Hin Ta & Hin Yai rocks' },
      { time: '18:00', activity: 'Sunset at the Jungle Club \ud83c\udf05 \u2014 Famous hilltop bar with infinity pool' },
      { time: 'Evening', activity: 'Friday Night Walking Market \u2014 Fisherman\u2019s Village \u2014 street food, live music, artisan stalls' },
    ],
    note: 'The Friday night market is one of Samui\u2019s best \u2014 our timing is perfect!',
    images: [
      'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=600&q=80',
      'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80',
      'https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=600&q=80',
    ],
  },
  {
    id: 'day10',
    day: 'Day 10',
    date: 'Sat, 25 Apr',
    title: 'Ang Thong Marine Park',
    location: 'Koh Samui',
    weather: '30\u00b0C, Sunny',
    items: [
      { time: '08:00', activity: 'Ang Thong National Marine Park \ud83c\udfde\ufe0f \u2014 Full-day boat tour \u2014 42 emerald islands' },
      { time: '', activity: 'Kayak through the Emerald Lake \u2014 saltwater lagoon inside a volcanic crater' },
      { time: '', activity: 'Hike to Koh Wua Talap viewpoint \u2014 jaw-dropping panorama' },
      { time: '', activity: 'Snorkelling in crystal-clear waters' },
      { time: '', activity: 'Beach time on pristine white sand' },
    ],
    note: 'Ang Thong is THE highlight of Koh Samui \u2014 book through Silavadee concierge.',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Emerald_Pool_%28Sa_Morakot%29.jpg/600px-Emerald_Pool_%28Sa_Morakot%29.jpg',
      'https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?w=600&q=80',
      'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80',
    ],
  },
  {
    id: 'day11',
    day: 'Day 11',
    date: 'Sun, 26 Apr',
    title: 'Anniversary Day',
    location: 'Koh Samui',
    weather: '31\u00b0C, Warm',
    items: [
      { time: 'Morning', activity: 'Sunrise yoga at Silavadee' },
      { time: 'Daytime', activity: 'Beach day at Choeng Mon \ud83c\udfd6\ufe0f \u2014 Calm crescent bay, crystal-clear water, total serenity' },
      { time: 'Evening', activity: 'Private Anniversary Dinner \u2764\ufe0f \u2014 Candlelit table on the rocks at Silavadee, overlooking the sea \u2014 just for us' },
    ],
    note: '25 years together \u2014 ask Silavadee at check-in to arrange our private dinner on the rocks.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
      'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=600&q=80',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80',
    ],
  },
  {
    id: 'day12',
    day: 'Day 12',
    date: 'Mon, 27 Apr',
    title: 'Last Day in Paradise',
    location: 'Koh Samui',
    weather: '30\u00b0C, Sunny',
    items: [
      { time: 'Morning', activity: 'Thai cooking class \ud83c\udf5c \u2014 Green curry, pad thai, tom yum, mango sticky rice' },
      { time: 'Afternoon', activity: 'Final pool & beach time \u2014 make the most of every last minute' },
      { time: 'Evening', activity: 'Fresh seafood beachfront dinner \u2014 toes in the sand, waves on the shore' },
    ],
    note: 'Pack tonight \u2014 leave Silavadee by 09:45 tomorrow for the 11:45 flight. Arrange transfer at check-in.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80',
      'https://images.unsplash.com/photo-1540202404-a2f29016b523?w=600&q=80',
    ],
  },
  {
    id: 'day13',
    day: 'Day 13',
    date: 'Tue, 28 Apr',
    title: 'Return to Bangkok',
    location: 'Koh Samui \u2192 Bangkok',
    weather: '34\u00b0C, Hot',
    items: [
      { time: '07:30', activity: 'Breakfast at Silavadee \u2014 last morning' },
      { time: '09:45', activity: 'Depart for Samui Airport' },
      {
        time: '11:45',
        activity: 'PG130 Koh Samui \u2192 Bangkok \u2708\ufe0f',
        bookingInfo: [
          'Bangkok Airways PG130',
          'Ref: EYK4NV',
          'Seats: 17A & 17F',
          '20kg checked + 7kg carry-on',
        ],
      },
      { time: '13:00', activity: 'Arrive Bangkok \u2014 taxi to Park Hyatt' },
      {
        time: '~14:15',
        activity: 'Check in Park Hyatt Bangkok',
        bookingInfo: [
          'Park Hyatt Bangkok',
          'Conf: 5129.127.037',
          'PIN: 3678',
          'King Room, City View \u2014 1 night',
        ],
      },
      { time: '16:30', activity: 'ICONSIAM \ud83d\udecd\ufe0f \u2014 Riverside mega-mall. Indoor floating market \u2014 authentic street food from every region' },
      { time: '18:30', activity: 'Vertigo & Moon Bar \ud83c\udf78 \u2014 Banyan Tree, 61st floor. Arrive for sunset \u2014 iconic rooftop' },
      { time: 'Evening', activity: 'Dinner near the hotel or optional Sukhumvit / Thonglor if energy allows' },
    ],
    note: 'Vertigo: smart casual, no flip-flops. Arrive by 18:30 for sunset tables.',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Bangkok_Night_Wikimedia_Commons.jpg/600px-Bangkok_Night_Wikimedia_Commons.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Floating_market_at_Damnoen_Saduak_1.JPG/600px-Floating_market_at_Damnoen_Saduak_1.JPG',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Grand_Palace%2C_Bangkok_P1100456.JPG/600px-Grand_Palace%2C_Bangkok_P1100456.JPG',
    ],
  },
  {
    id: 'day14',
    day: 'Day 14',
    date: 'Wed, 29 Apr',
    title: 'Golden Temples, Last Day & Fly Home',
    location: 'Bangkok \u2192 London',
    weather: '35\u00b0C, Clear',
    items: [
      { time: '07:00', activity: 'Early breakfast at Park Hyatt' },
      { time: '07:30', activity: 'Wat Pho \u2014 The Reclining Buddha. 150 feet of gold. Go early to beat the crowds and heat' },
      { time: '09:00', activity: 'Grand Palace & Wat Phra Kaew \u2014 Thailand\u2019s most sacred temple. Cover shoulders & knees' },
      { time: '~10:30', activity: 'Taxi back to Park Hyatt area' },
      { time: '12:00\u201318:00', activity: 'Free afternoon \u2014 Penthouse Bar + Grill at Park Hyatt (levels 34\u201336), Shopping at Central Embassy or Siam Paragon, Jim Thompson House, or Bang Kachao (Bangkok\u2019s Green Lung \u2014 cycle through a jungle oasis)' },
      { time: '19:00', activity: 'Collect bags, taxi to BKK Airport' },
      {
        time: '22:35',
        activity: 'British Airways BKK \u2192 London Gatwick \u2708\ufe0f',
        bookingInfo: [
          'British Airways BA 2230',
          'Ref: Y3K2WE',
          'Seats: 13D & 13E',
          'BKK 22:35 \u2192 LGW 05:55+1',
          'Premium Economy Semi-Flex',
        ],
      },
    ],
    note: 'Temples first thing \u2014 beat the heat and crowds. Check out at noon \u2014 Park Hyatt stores bags. Connected to Central Embassy. Later BA flight (22:35) means a relaxed final evening!',
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Panorama_of_Reclining_Buddha_-_Wat_Pho.jpg/600px-Panorama_of_Reclining_Buddha_-_Wat_Pho.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Grand_Palace%2C_Bangkok_P1100456.JPG/600px-Grand_Palace%2C_Bangkok_P1100456.JPG',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Bangkok_Night_Wikimedia_Commons.jpg/600px-Bangkok_Night_Wikimedia_Commons.jpg',
    ],
  },
  {
    id: 'day15',
    day: 'Day 15',
    date: 'Thu, 30 Apr',
    title: 'Home',
    location: 'London',
    weather: '',
    items: [
      { time: '05:55', activity: 'Arrive London Gatwick \ud83c\udfe0 \u2014 Direct flight, no connection!' },
    ],
    note: 'Home sweet home \u2014 what a trip.',
    images: [],
  },
];

export const BUDGET = [
  { cat: 'British Airways Flights', detail: 'LGW \u2194 BKK return \u2014 Premium Economy Semi-Flex' },
  { cat: 'Bangkok Airways', detail: 'BKK\u2192HKT + HKT\u2192USM + USM\u2192BKK (3 flights)' },
  { cat: 'M\u00f6venpick Ploenchit', detail: 'Bangkok \u2014 1 night, Deluxe King' },
  { cat: 'The Slate, Phuket', detail: '5 nights (4+1), Pearl Bed Suite' },
  { cat: 'Silavadee Pool Spa', detail: 'Koh Samui \u2014 4 nights, Ocean View Pool Villa' },
  { cat: 'Park Hyatt Bangkok', detail: '1 night, King Room City View' },
];

export const DOCUMENTS = [
  {
    category: 'Flights',
    icon: '✈️',
    docs: [
      { label: 'British Airways — Flights', sublabel: 'LGW ↔ BKK · BA 2231 / BA 2230', filename: 'BA Flights.pdf' },
      { label: 'Bangkok Airways — All Flights', sublabel: 'PG273 + PG254 + PG130', filename: 'Bangkok Airways - Reservation.pdf' },
      { label: 'Simon — Travel Reservation', sublabel: '18 Apr', filename: 'Travel Reservation 18APR for SIMON SHAH.pdf' },
      { label: 'Yevgeniya — Travel Reservation', sublabel: '18 Apr', filename: 'Travel Reservation 18APR for YEVGENIYA SHAH.pdf' },
    ],
  },
  {
    category: 'Hotels',
    icon: '🏨',
    docs: [
      { label: 'Mövenpick Ploenchit', sublabel: 'Bangkok · 1 night', filename: 'Movenpick Booking.com_ Confirmation.pdf' },
      { label: 'The Slate — Booking 1', sublabel: 'Phuket · Pearl Bed Suite', filename: 'Slate Booking.com_ Confirmation.pdf' },
      { label: 'The Slate — Booking 2', sublabel: 'Phuket · Extension night', filename: 'Slate 2 booking.pdf' },
      { label: 'The Slate — Payment', sublabel: 'Payment confirmation', filename: 'SlatePayment.pdf' },
      { label: 'Silavadee Pool Spa Resort', sublabel: 'Koh Samui · 4 nights', filename: 'Silavadee Koh Samui 22-27.pdf' },
      { label: 'Park Hyatt Bangkok', sublabel: '1 night · King City View', filename: 'Park Hyatt.pdf' },
    ],
  },
  {
    category: 'Insurance & Emergency',
    icon: '🛡️',
    docs: [
      { label: 'Admiral Travel Insurance', sublabel: 'Platinum · Policy ADM/4717318/2025 · Worldwide', filename: 'Admiral Travel Insurance.pdf' },
      { label: 'Passports', sublabel: 'Photocopies — Simon & Yevgeniya', filename: 'Passports.pdf' },
    ],
  },
  {
    category: 'Itinerary',
    icon: '📋',
    docs: [
      { label: 'Full Itinerary', sublabel: 'Bangkok Anniversary Trip', filename: 'Bangkok_Itinerary_Anniversary.docx' },
    ],
  },
];

export const BOOKING_DOCS = {
  'British Airways BA 2231': ['BA Flights.pdf'],
  'British Airways BA 2230': ['BA Flights.pdf'],
  'Bangkok Airways PG273': ['Bangkok Airways - Reservation.pdf'],
  'Bangkok Airways PG254': ['Bangkok Airways - Reservation.pdf'],
  'Bangkok Airways PG130': ['Bangkok Airways - Reservation.pdf'],
  'Mövenpick BDMS Ploenchit': ['Movenpick Booking.com_ Confirmation.pdf'],
  'The Slate, Phuket': ['Slate Booking.com_ Confirmation.pdf', 'Slate 2 booking.pdf'],
  'Silavadee Pool Spa Resort': ['Silavadee Koh Samui 22-27.pdf'],
  'Park Hyatt Bangkok': ['Park Hyatt.pdf'],
};

export const CHECKLIST_ITEMS = [
  'Book British Airways flights (LGW\u2192BKK direct return)',
  'Book Bangkok Airways BKK\u2192HKT, HKT\u2192USM, USM\u2192BKK',
  'Book M\u00f6venpick Ploenchit (1 night)',
  'Book The Slate, Phuket (5 nights)',
  'Book Silavadee Pool Spa Resort (4 nights)',
  'Book Park Hyatt Bangkok (1 night)',
  'Check passport expiry (6+ months)',
  'Travel insurance \u2014 Admiral Platinum (ADM/4717318/2025)',
  'Book Phang Nga Bay speedboat tour',
  'Book Phi Phi Islands speedboat day trip',
  'Book Ang Thong Marine Park tour via Silavadee concierge',
  'Reserve Black Ginger Restaurant (ask Slate reception Day 3)',
  'Arrange private anniversary dinner at Silavadee (ask at check-in)',
  'Book Vertigo & Moon Bar (arrive 18:30 for sunset)',
  'Pack reef-safe sunscreen & seasickness tablets',
  'Download offline maps (Google Maps)',
  'Download Grab app (Thai Uber)',
  'Notify bank of travel dates',
  'Pack power adapter (Type A/B/C for Thailand)',
  'Pack smart casual outfit for Vertigo (no flip-flops)',
  'Buy waterproof phone pouch',
  'Pack cover-up for temples (shoulders & knees)',
];
