export const TRIP_START = new Date('2026-04-10T00:00:00');

export const CITIES = [
  {
    name: 'Bangkok',
    subtitle: 'The City of Angels',
    dayRange: [1, 4],
    heroImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Bangkok_Night_Wikimedia_Commons.jpg/1600px-Bangkok_Night_Wikimedia_Commons.jpg',
  },
  {
    name: 'Chiang Mai',
    subtitle: 'The Rose of the North',
    dayRange: [5, 6],
    heroImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Chiang-Mai_Thailand_Wat-Chedi-Luang-01.jpg/1600px-Chiang-Mai_Thailand_Wat-Chedi-Luang-01.jpg',
  },
  {
    name: 'Krabi',
    subtitle: 'Emerald Waters & Limestone Dreams',
    dayRange: [7, 10],
    heroImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Railay.jpg/1600px-Railay.jpg',
  },
];

export const DAYS = [
  {
    id: 'day1',
    day: 'Day 1',
    date: 'Fri, 10 Apr',
    title: 'Arrival in Bangkok',
    location: 'Bangkok',
    weather: '34\u00b0C, Sunny & Humid',
    items: [
      { time: 'Afternoon', activity: 'Arrive at Suvarnabhumi Airport, transfer to hotel', cost: '' },
      { time: 'Evening', activity: 'Check in to hotel near Khao San Road', cost: '~\u0e3f2,500/night' },
      { time: 'Night', activity: 'Street food tour \u2013 Pad Thai, mango sticky rice, Thai iced tea', cost: '~\u0e3f300' },
      { time: 'Late Night', activity: 'Walk along the Chao Phraya River', cost: '' },
    ],
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Bangkok_Night_Wikimedia_Commons.jpg/600px-Bangkok_Night_Wikimedia_Commons.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Wat_Arun_Ratchawararam_and_Royal_Barge_Procession.JPG/600px-Wat_Arun_Ratchawararam_and_Royal_Barge_Procession.JPG',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Thai_Food_in_street.JPG/600px-Thai_Food_in_street.JPG',
    ],
  },
  {
    id: 'day2',
    day: 'Day 2',
    date: 'Sat, 11 Apr',
    title: 'Bangkok Temples & Culture',
    location: 'Bangkok',
    weather: '35\u00b0C, Partly Cloudy',
    items: [
      { time: 'Morning', activity: 'Grand Palace & Wat Phra Kaew (Temple of the Emerald Buddha)', cost: '\u0e3f500 entry' },
      { time: 'Midday', activity: 'Wat Pho \u2013 the Reclining Buddha & traditional Thai massage', cost: '\u0e3f300 entry + \u0e3f400 massage' },
      { time: 'Afternoon', activity: 'Lunch at Thip Samai (famous Pad Thai)', cost: '~\u0e3f200' },
      { time: 'Evening', activity: 'Wat Arun at sunset \u2013 cross the river by ferry', cost: '\u0e3f100 entry' },
      { time: 'Night', activity: 'Rooftop dinner & drinks at a sky bar', cost: '~\u0e3f2,000' },
    ],
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Grand_Palace%2C_Bangkok_P1100456.JPG/600px-Grand_Palace%2C_Bangkok_P1100456.JPG',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Panorama_of_Reclining_Buddha_-_Wat_Pho.jpg/600px-Panorama_of_Reclining_Buddha_-_Wat_Pho.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Wat_Arun_Ratchawararam_and_Royal_Barge_Procession.JPG/600px-Wat_Arun_Ratchawararam_and_Royal_Barge_Procession.JPG',
    ],
  },
  {
    id: 'day3',
    day: 'Day 3',
    date: 'Sun, 12 Apr',
    title: 'Songkran Festival \u2013 Water Festival!',
    location: 'Bangkok',
    weather: '35\u00b0C, Hot & Festive',
    items: [
      { time: 'All Day', activity: "Songkran Water Festival \u2013 Thailand's New Year celebration!", cost: '' },
      { time: 'Morning', activity: 'Buy water guns & waterproof bags at MBK Center', cost: '~\u0e3f500' },
      { time: 'Afternoon', activity: 'Water fight at Silom Road \u2013 the biggest Songkran party in Bangkok', cost: '' },
      { time: 'Evening', activity: 'Traditional Songkran ceremony at a temple \u2013 water blessings', cost: '' },
      { time: 'Night', activity: 'Night market food crawl at Jodd Fairs', cost: '~\u0e3f500' },
    ],
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Chiang-Mai_Thailand_Songkran-Festival-2017-02.jpg/600px-Chiang-Mai_Thailand_Songkran-Festival-2017-02.jpg',
      'https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=600&q=80',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Thai_Food_in_street.JPG/600px-Thai_Food_in_street.JPG',
    ],
  },
  {
    id: 'day4',
    day: 'Day 4',
    date: 'Mon, 13 Apr',
    title: 'Floating Markets & Local Life',
    location: 'Bangkok',
    weather: '34\u00b0C, Humid',
    items: [
      { time: 'Early Morning', activity: 'Damnoen Saduak Floating Market (1.5hr drive)', cost: '~\u0e3f1,500 tour' },
      { time: 'Midday', activity: 'Boat ride through the canals & market shopping', cost: '~\u0e3f300' },
      { time: 'Afternoon', activity: 'Chatuchak Weekend Market \u2013 huge open-air market', cost: '~\u0e3f500 shopping' },
      { time: 'Evening', activity: 'Thai cooking class \u2013 learn green curry & tom yum', cost: '~\u0e3f1,500' },
      { time: 'Night', activity: 'Pack for Chiang Mai, early flight tomorrow', cost: '' },
    ],
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Floating_market_at_Damnoen_Saduak_1.JPG/600px-Floating_market_at_Damnoen_Saduak_1.JPG',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Longtail_boat_at_Maya_bay.JPG/600px-Longtail_boat_at_Maya_bay.JPG',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
    ],
  },
  {
    id: 'day5',
    day: 'Day 5',
    date: 'Tue, 14 Apr',
    title: 'Fly to Chiang Mai',
    location: 'Chiang Mai',
    weather: '33\u00b0C, Warm & Clear',
    items: [
      { time: 'Morning', activity: 'Fly Bangkok \u2192 Chiang Mai (1hr flight)', cost: '~\u0e3f2,000 pp' },
      { time: 'Midday', activity: 'Check into boutique hotel in Old City', cost: '~\u0e3f2,000/night' },
      { time: 'Afternoon', activity: 'Explore the Old City temples \u2013 Wat Chedi Luang, Wat Phra Singh', cost: '~\u0e3f100' },
      { time: 'Evening', activity: 'Khao Soi (coconut curry noodles) at a local favourite', cost: '~\u0e3f150' },
      { time: 'Night', activity: 'Night Bazaar \u2013 crafts, souvenirs, street food', cost: '~\u0e3f500' },
    ],
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Chiang-Mai_Thailand_Wat-Chedi-Luang-01.jpg/600px-Chiang-Mai_Thailand_Wat-Chedi-Luang-01.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Phra_That_Doi_Suthep_Chiang_Mai.jpg/600px-Phra_That_Doi_Suthep_Chiang_Mai.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/CHIANG_MAI_NIGHT_BAZAAR_THAILAND_FEB_2012_%286869571256%29.jpg/600px-CHIANG_MAI_NIGHT_BAZAAR_THAILAND_FEB_2012_%286869571256%29.jpg',
    ],
  },
  {
    id: 'day6',
    day: 'Day 6',
    date: 'Wed, 15 Apr',
    title: 'Elephants & Jungle',
    location: 'Chiang Mai',
    weather: '32\u00b0C, Partly Cloudy',
    items: [
      { time: 'Morning', activity: 'Ethical elephant sanctuary visit \u2013 feed & walk with elephants', cost: '~\u0e3f2,500 pp' },
      { time: 'Afternoon', activity: 'Bamboo rafting through the jungle', cost: 'Included' },
      { time: 'Late Afternoon', activity: 'Doi Suthep temple \u2013 panoramic views of Chiang Mai', cost: '\u0e3f50 entry' },
      { time: 'Evening', activity: 'Anniversary dinner \u2013 upscale Northern Thai cuisine', cost: '~\u0e3f3,000' },
      { time: 'Night', activity: 'Couples spa treatment \u2013 herbal compress massage', cost: '~\u0e3f2,000' },
    ],
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Mahout_Elephant_Nature_Park.JPG/600px-Mahout_Elephant_Nature_Park.JPG',
      'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Phra_That_Doi_Suthep_Chiang_Mai.jpg/600px-Phra_That_Doi_Suthep_Chiang_Mai.jpg',
    ],
  },
  {
    id: 'day7',
    day: 'Day 7',
    date: 'Thu, 16 Apr',
    title: 'Travel to Krabi',
    location: 'Krabi',
    weather: '31\u00b0C, Tropical & Warm',
    items: [
      { time: 'Morning', activity: 'Fly Chiang Mai \u2192 Krabi (with connection)', cost: '~\u0e3f3,000 pp' },
      { time: 'Afternoon', activity: 'Check into beachfront resort at Ao Nang', cost: '~\u0e3f3,500/night' },
      { time: 'Late Afternoon', activity: 'Relax on Ao Nang Beach', cost: '' },
      { time: 'Evening', activity: 'Seafood BBQ dinner on the beach', cost: '~\u0e3f1,000' },
      { time: 'Night', activity: 'Beach bar cocktails with live music', cost: '~\u0e3f500' },
    ],
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Railay.jpg/600px-Railay.jpg',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80',
    ],
  },
  {
    id: 'day8',
    day: 'Day 8',
    date: 'Fri, 17 Apr',
    title: 'Island Hopping \u2013 4 Islands Tour',
    location: 'Krabi',
    weather: '31\u00b0C, Sunny',
    items: [
      { time: 'Morning', activity: 'Four Islands tour by longtail boat', cost: '~\u0e3f1,500 pp' },
      { time: 'Mid-Morning', activity: 'Snorkel at Koh Poda \u2013 crystal clear water', cost: 'Included' },
      { time: 'Midday', activity: 'Beach lunch on Tup Island (the sandbar)', cost: 'Included' },
      { time: 'Afternoon', activity: 'Explore Phra Nang Cave Beach & swim at Chicken Island', cost: '' },
      { time: 'Evening', activity: 'Sunset kayaking at Railay Beach', cost: '~\u0e3f800' },
      { time: 'Night', activity: 'Night market dinner at Krabi Town', cost: '~\u0e3f400' },
    ],
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Longtail_boat_at_Maya_bay.JPG/600px-Longtail_boat_at_Maya_bay.JPG',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/KohPhiPhi.JPG/600px-KohPhiPhi.JPG',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=600&q=80',
    ],
  },
  {
    id: 'day9',
    day: 'Day 9',
    date: 'Sat, 18 Apr',
    title: 'Relaxation & Adventure',
    location: 'Krabi',
    weather: '32\u00b0C, Mostly Sunny',
    items: [
      { time: 'Morning', activity: 'Emerald Pool & Hot Springs \u2013 swim in natural pools', cost: '\u0e3f200 entry' },
      { time: 'Midday', activity: 'Tiger Cave Temple \u2013 1,260 steps to the summit!', cost: '' },
      { time: 'Afternoon', activity: 'Spa afternoon \u2013 full body Thai massage', cost: '~\u0e3f1,500' },
      { time: 'Evening', activity: 'Final anniversary dinner \u2013 cliffside restaurant overlooking the sea', cost: '~\u0e3f3,000' },
      { time: 'Night', activity: 'Lantern release on the beach', cost: '~\u0e3f200' },
    ],
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Emerald_Pool_%28Sa_Morakot%29.jpg/600px-Emerald_Pool_%28Sa_Morakot%29.jpg',
      'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=600&q=80',
      'https://images.unsplash.com/photo-1540202404-a2f29016b523?w=600&q=80',
    ],
  },
  {
    id: 'day10',
    day: 'Day 10',
    date: 'Sun, 19 Apr',
    title: 'Departure Day',
    location: 'Krabi \u2192 Home',
    weather: '31\u00b0C, Clear',
    items: [
      { time: 'Morning', activity: 'Last breakfast by the beach & morning swim', cost: '' },
      { time: 'Midday', activity: 'Last-minute souvenir shopping at Ao Nang', cost: '~\u0e3f1,000' },
      { time: 'Afternoon', activity: 'Transfer to Krabi Airport', cost: '~\u0e3f500' },
      { time: 'Evening', activity: 'Fly home \u2013 full of memories!', cost: '' },
    ],
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
      'https://images.unsplash.com/photo-1504214208698-ea1916a2195a?w=600&q=80',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Grand_Palace%2C_Bangkok_P1100456.JPG/600px-Grand_Palace%2C_Bangkok_P1100456.JPG',
    ],
  },
];

export const BUDGET = [
  { cat: 'Flights', detail: 'Return flights + domestic flights', cost: '~\u0e3f25,000 pp' },
  { cat: 'Hotels', detail: 'Bangkok (4n) + Chiang Mai (2n) + Krabi (3n)', cost: '~\u0e3f25,000 total' },
  { cat: 'Food & Drink', detail: 'Street food, restaurants, sky bars', cost: '~\u0e3f15,000' },
  { cat: 'Activities', detail: 'Tours, temples, elephant sanctuary, cooking class', cost: '~\u0e3f15,000' },
  { cat: 'Transport', detail: 'Taxis, boats, tuk-tuks, ferries', cost: '~\u0e3f5,000' },
  { cat: 'Shopping', detail: 'Markets, souvenirs, Songkran gear', cost: '~\u0e3f5,000' },
  { cat: 'Spa & Wellness', detail: 'Massages, spa treatments', cost: '~\u0e3f5,000' },
  { cat: 'Misc & Buffer', detail: 'Tips, SIM card, insurance, emergencies', cost: '~\u0e3f5,000' },
];

export const CHECKLIST_ITEMS = [
  'Book flights',
  'Book hotels/resorts',
  'Apply for travel insurance',
  'Check passport expiry (6+ months)',
  'Pack lightweight & waterproof clothes',
  'Download offline maps (Google Maps / Maps.me)',
  'Get Thai Baht (or use Wise card)',
  'Buy waterproof phone pouch for Songkran',
  'Pack reef-safe sunscreen & mosquito repellent',
  'Book elephant sanctuary in advance',
  'Notify bank of travel dates',
  'Pack power adapter (Type A/B/C for Thailand)',
  'Download Grab app (Thai Uber)',
  'Book airport transfer',
  'Print or save hotel confirmations',
  'Pack small daypack for island tours',
];
